version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: exampleapp
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: password
    ports:
      - "0.0.0.0:5432:5432" # bind to host for populating scripts
    volumes:
      - /var/lib/postgresql/16/main:/var/lib/postgresql/16/main
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - example_network 

  login-service:
    image: local-registry:5200/login-service:latest
    container_name: login_service_container
    ports:
      - "5000:5000"
    networks:
      - example_network

  user-service:
    image: local-registry:5200/user-service:latest
    container_name: user_service_container
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    networks:
      - example_network

  product-service:
    image: local-registry:5200/product-service:latest
    container_name: product_service_container
    depends_on:
      - postgres
    ports:
      - "5002:5002"
    networks:
      - example_network

  order-service:
    image: local-registry:5200/order-service:latest
    container_name: order_service_container
    depends_on:
      - postgres
    ports:
      - "5003:5003"
    networks:
      - example_network

  frontend:
    image: local-registry:5200/frontend-service:latest
    container_name: frontend_container
    depends_on:
      - user-service
      - product-service
      - order-service
    ports:
      - "5100:5100"
    networks:
      - example_network

networks:
  example_network:
    driver: bridge
