version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: exampleapp
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: password
    ports:
      - "0.0.0.0:5432:5432" # bind to host for populating scripts
    volumes:
      - /var/lib/postgresql/16/main:/var/lib/postgresql/16/main
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - example_network 

  login-service:
    build: ./login-service/
    container_name: login_service_container
    command: gunicorn -b 0.0.0.0:5000 'app:app' --reload
    ports:
      - "5000:5000"
    volumes:
      - ./login-service/:/app
    networks:
      - example_network

  user-service:
    build: ./user-service/
    container_name: user_service_container
    command: gunicorn -b 0.0.0.0:5001 'app:app' --reload
    depends_on:
      - postgres
    ports:
      - "5001:5001"
    volumes:
      - ./user-service/:/app
    networks:
      - example_network

  product-service:
    build: ./product-service/
    container_name: product_service_container
    command: gunicorn -b 0.0.0.0:5002 'app:app' --reload
    depends_on:
      - postgres
    ports:
      - "5002:5002"
    volumes:
      - ./product-service/:/app
    networks:
      - example_network

  order-service:
    build: ./order-service/
    container_name: order_service_container
    command: gunicorn -b 0.0.0.0:5003 'app:app' --reload
    depends_on:
      - postgres
    ports:
      - "5003:5003"
    volumes:
      - ./order-service/:/app
    networks:
      - example_network

  frontend:
    build: ./frontend-service/
    container_name: frontend_container
    command: gunicorn -b 0.0.0.0:5100 'app:app' --reload
    depends_on:
      - user-service
      - product-service
      - order-service
    ports:
      - "5100:5100"
    volumes:
      - ./frontend-service/:/app
    networks:
      - example_network

networks:
  example_network:
    driver: bridge
